###### Accepts the following parametrs:
#
# bridge_path                             (*) path to the bridge folder (also used in templates)
# bridge_bin_url                          (*) url from which to download bridge binary
# bridge_bin_sha256                       (*) sha256 checksum of the binary
# bridge_service_name                     (*) name to be used for bridge service
# bridge_deposit_relay_gas                bridge config option (used only in templates)
# bridge_withdraw_relay_gas               bridge config option (used only in templates)
# bridge_withdraw_confirm_gas             bridge config option (used only in templates)
# bridge_home_required_confirmations      bridge config option (used only in templates)
# bridge_home_poll_interval               bridge config option (used only in templates)
# bridge_home_request_timeout             bridge config option (used only in templates)
# bridge_foreign_required_confirmations   bridge config option (used only in templates)
# bridge_foreign_poll_interval            bridge config option (used only in templates)
# bridge_foreign_request_timeout          bridge config option (used only in templates)
# db_toml_location                        path to bridge db.toml **on local machine**
# restart_delay_sec                       (*) delay in seconds between restarts of brige service. Set to 0 to omit this option (used only in templates)
# bridge_keystore_folder                  (*) folder to store keystore files
# bridge_home_password_file               (*) name of the file with password
# bridge_foreign_password_file            (*) name of the file with password
# home_rpc_url                            url of home-side rpc endpoint
# foreign_rpc_url                         url of foreign-sode rpc endpoint
# home_rpc_port                           port of home-side rpc endpoint
# foreign_rpc_port                        port of foreign-side rpc endpoint
#
---
bridge_path: "{{ base_path }}/bridge"
bridge_bin_url: "https://s3.amazonaws.com/poa-bridge-iterim/release-v0.3.0/bridge"
bridge_bin_sha256: "4cfbba6f00fe6bbbd002b71ab4610c4bca06931496ee18fdbfd124d823b88bcb"
bridge_service_name: "bridge"
db_toml_location: ""

home_rpc_port: 443
foreign_rpc_port: 443

restart_delay_sec: 2

bridge_keystore_folder: "keys"
bridge_home_password_file: "home-password.txt"
bridge_foreign_password_file: "foreign-password.txt"

# set to -1 to use bridge binary default values
bridge_home_request_timeout: 360
bridge_foreign_request_timeout: 360

bridge_authorities: []

# set to empty string to use default value
bridge_home_gas_price_oracle_url: ""
# set to -1 to use default value
bridge_home_gas_price_timeout: -1
# set to empty string to use default value
bridge_home_gas_price_speed: ""
# set to -1 to use default value
bridge_home_default_gas_price: -1

# set to empty string to use default value
bridge_foreign_gas_price_oracle_url: ""
# set to -1 to use default value
bridge_foreign_gas_price_timeout: -1
# set to empty string to use default value
bridge_foreign_gas_price_speed: ""
# set to -1 to use default value
bridge_foreign_default_gas_price: -1
