---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: monitor-host
    groups:
      - example
    children:
      - monitor
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ./converge.yml
  inventory:
    host_vars:
      monitor-host:
        MONITOR_PORT: 3003
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../tests/*
scenario:
  name: monitor
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
