---
- hosts: all
  become: yes
  gather_facts: no
  # vars:
  #   home_signer_address: "0x{{ (signer_keyfile|from_json).address }}"
  #   home_signer_keyfile: '{{ signer_keyfile }}'
  #   home_signer_password: "{{ signer_password }}"
  #   foreign_signer_address: "{{ home_signer_address }}"
  #   foreign_signer_keyfile: '{{ home_signer_keyfile }}'
  #   foreign_signer_password: "{{ home_signer_password }}"
  #   bridge_home_password_file: "password.txt"
  #   bridge_foreign_password_file: "password.txt"
  roles:
    - backward-compatibility
    - authority-preconf
    - bridge
