---
version: '3.0'
services:
  molecule_runner:
    build:
      context: ..
      dockerfile: deployment-e2e/Dockerfile
    restart: 'no'
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/mono
