---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: True
  options:
    config-data:
      ignore: ../../hosts.yml
platforms:
  - name: ui-host
    groups:
      - example
    children:
      - ui
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: True
    options:
      r: ["bug"]
  playbooks:
    prepare: ../prepare.yml
    converge: ../../../deployment/site.yml
  inventory:
    host_vars:
      ui-host:
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  lint:
    name: flake8
  additional_files_or_dirs:
    - ../../tests/*
scenario:
  name: ui
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
