version: '3'
services:
  parity1:
    build: parity
    ports:
      - "8541:8545"
  parity2:
    build: parity
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  bridge:
    build: ..
    environment:
      - NODE_ENV=production
      - BRIDGE_MODE=NATIVE_TO_ERC
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
      - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
      - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_SPEED_TYPE=standard
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
    command: "true"
  bridge-erc:
    build: ..
    environment:
      - NODE_ENV=production
      - BRIDGE_MODE=ERC_TO_ERC
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
      - FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
      - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
      - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_SPEED_TYPE=standard
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
    command: "true"
  bridge-erc-native:
    build: ..
    environment:
      - NODE_ENV=production
      - BRIDGE_MODE=ERC_TO_NATIVE
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
      - FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
      - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
      - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_SPEED_TYPE=standard
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
    command: "true"
  e2e:
    build: .
    command: "true"
