const BRIDGE_MODES = {
  NATIVE_TO_ERC: 'NATIVE_TO_ERC',
  ERC_TO_ERC: 'ERC_TO_ERC',
  ERC_TO_NATIVE: 'ERC_TO_NATIVE',
  NATIVE_TO_ERC_V1: 'NATIVE_TO_ERC_V1',
  ARBITRARY_MESSAGE: 'ARBITRARY_MESSAGE',
  AMB_ERC_TO_ERC: 'AMB_ERC_TO_ERC',
  AMB_NATIVE_TO_ERC: 'AMB_NATIVE_TO_ERC',
  STAKE_AMB_ERC_TO_ERC: 'STAKE_AMB_ERC_TO_ERC'
}

const ERC_TYPES = {
  ERC20: 'ERC20',
  ERC677: 'ERC677'
}

const FEE_MANAGER_MODE = {
  ONE_DIRECTION: 'ONE_DIRECTION',
  BOTH_DIRECTIONS: 'BOTH_DIRECTIONS',
  ONE_DIRECTION_STAKE: 'ONE_DIRECTION_STAKE',
  UNDEFINED: 'UNDEFINED'
}

const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

module.exports = {
  BRIDGE_MODES,
  ERC_TYPES,
  FEE_MANAGER_MODE,
  ZERO_ADDRESS
}
