---
- name: Install Oracle
  hosts: oracle
  become: true
  roles:
    - { role: oracle }
- name: Install UI
  hosts: ui
  become: true
  roles:
    - { role: ui }
- name: Install Monitor
  hosts: monitor
  become: true
  roles:
    - { role: monitor }
