---
version: '3'
networks:
  ultimate:
    external: true
services:
  parity1:
    build: ../parity
    ports:
    - "8541:8545"
    networks:
      - ultimate
  parity2:
    build:
      context: ../parity
      dockerfile: Dockerfile-foreign
    ports:
    - "8542:8545"
    networks:
      - ultimate
  redis:
    image: "redis:4"
    networks:
      - ultimate
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    networks:
      - ultimate
  oracle:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/oracle.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-erc20:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/oracle-erc20.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-erc20-native:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/oracle-erc20-native.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-amb:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
      - NODE_ENV=production
      - BRIDGE_MODE=ARBITRARY_MESSAGE
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x0AEe1FCD12dDFab6265F7f8956e6E012A9Fe4Aa0
      - FOREIGN_BRIDGE_ADDRESS=0x0AEe1FCD12dDFab6265F7f8956e6E012A9Fe4Aa0
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_SPEED_TYPE=standard
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_GAS_PRICE_FACTOR=1
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_FACTOR=1
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
    command: "true"
    networks:
      - ultimate
  ui:
    build:
      context: ..
      dockerfile: ui/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/ui.env
    command: "true"
    networks:
      - ultimate
  ui-erc20:
    build:
      context: ..
      dockerfile: ui/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/ui-erc20.env
    command: "true"
    networks:
      - ultimate
  ui-erc20-native:
    build:
      context: ..
      dockerfile: ui/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/ui-erc20-native.env
    command: "true"
    networks:
      - ultimate
  monitor:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/monitor.env
    entrypoint: yarn check-and-start
    ports:
      - "3010:3010"
    networks:
      - ultimate
  monitor-erc20:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/monitor-erc20.env
    entrypoint: yarn check-and-start
    ports:
      - "3011:3011"
    networks:
      - ultimate
  monitor-erc20-native:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/monitor-erc20-native.env
    entrypoint: yarn check-and-start
    ports:
      - "3012:3012"
    networks:
      - ultimate
  e2e:
    build:
      context: ..
      dockerfile: Dockerfile.e2e
    command: "true"
    networks:
      - ultimate
