---
version: '3'
services:
  parity1:
    build: ../parity
    ports:
    - "8541:8545"
  parity2:
    build:
      context: ../parity
      dockerfile: Dockerfile-foreign
    ports:
    - "8542:8545"
  redis:
    image: "redis:4"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
  oracle:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - BRIDGE_MODE=NATIVE_TO_ERC
    - QUEUE_URL=amqp://rabbit
    - REDIS_URL=redis://redis
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
    - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - HOME_GAS_PRICE_SPEED_TYPE=standard
    - HOME_GAS_PRICE_FALLBACK=1
    - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - HOME_GAS_PRICE_FACTOR=1
    - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - FOREIGN_GAS_PRICE_FALLBACK=1
    - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - FOREIGN_GAS_PRICE_FACTOR=0.1
    - HOME_POLLING_INTERVAL=500
    - FOREIGN_POLLING_INTERVAL=500
    - ALLOW_HTTP=yes
    command: "true"
  oracle-erc20:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - BRIDGE_MODE=ERC_TO_ERC
    - QUEUE_URL=amqp://rabbit
    - REDIS_URL=redis://redis
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
    - FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
    - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
    - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
    - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - HOME_GAS_PRICE_SPEED_TYPE=standard
    - HOME_GAS_PRICE_FALLBACK=1
    - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - HOME_GAS_PRICE_FACTOR=1
    - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - FOREIGN_GAS_PRICE_FALLBACK=1
    - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - FOREIGN_GAS_PRICE_FACTOR=0.1
    - HOME_POLLING_INTERVAL=500
    - FOREIGN_POLLING_INTERVAL=500
    - ALLOW_HTTP=yes
    command: "true"
  oracle-erc20-native:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - BRIDGE_MODE=ERC_TO_NATIVE
    - QUEUE_URL=amqp://rabbit
    - REDIS_URL=redis://redis
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
    - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
    - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - HOME_GAS_PRICE_SPEED_TYPE=standard
    - HOME_GAS_PRICE_FALLBACK=1
    - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - HOME_GAS_PRICE_FACTOR=1
    - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - FOREIGN_GAS_PRICE_FALLBACK=1
    - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - FOREIGN_GAS_PRICE_FACTOR=0.1
    - HOME_POLLING_INTERVAL=500
    - FOREIGN_POLLING_INTERVAL=500
    - ALLOW_HTTP=yes
    command: "true"
  ui:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - REACT_APP_HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - REACT_APP_FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - REACT_APP_FOREIGN_HTTP_PARITY_URL=http://localhost:8542
    - REACT_APP_HOME_HTTP_PARITY_URL=http://localhost:8541
    - REACT_APP_HOME_NATIVE_NAME=POA
    - REACT_APP_HOME_NETWORK_NAME=Sokol
    - REACT_APP_FOREIGN_NETWORK_NAME=Kovan
    - REACT_APP_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - REACT_APP_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - REACT_APP_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - REACT_APP_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - REACT_APP_HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_HOME_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_HOME_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_HOME_GAS_PRICE_FACTOR=1
    - REACT_APP_FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_FOREIGN_GAS_PRICE_FACTOR=1
    - PORT=3000
    command: "true"
  ui-erc20:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - REACT_APP_HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
    - REACT_APP_FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
    - REACT_APP_FOREIGN_HTTP_PARITY_URL=http://localhost:8542
    - REACT_APP_HOME_HTTP_PARITY_URL=http://localhost:8541
    - REACT_APP_HOME_NATIVE_NAME=POA
    - REACT_APP_HOME_NETWORK_NAME=Sokol
    - REACT_APP_FOREIGN_NETWORK_NAME=Kovan
    - REACT_APP_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - REACT_APP_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - REACT_APP_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - REACT_APP_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - REACT_APP_HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_HOME_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_HOME_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_HOME_GAS_PRICE_FACTOR=1
    - REACT_APP_FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_FOREIGN_GAS_PRICE_FACTOR=1
    - PORT=3000
    command: "true"
  ui-erc20-native:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - REACT_APP_HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - REACT_APP_FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - REACT_APP_FOREIGN_HTTP_PARITY_URL=http://localhost:8542
    - REACT_APP_HOME_HTTP_PARITY_URL=http://localhost:8541
    - REACT_APP_HOME_NATIVE_NAME=POA
    - REACT_APP_HOME_NETWORK_NAME=Sokol
    - REACT_APP_FOREIGN_NETWORK_NAME=Kovan
    - REACT_APP_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - REACT_APP_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - REACT_APP_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - REACT_APP_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - REACT_APP_HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_HOME_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_HOME_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_HOME_GAS_PRICE_FACTOR=1
    - REACT_APP_FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - REACT_APP_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - REACT_APP_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - REACT_APP_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - REACT_APP_FOREIGN_GAS_PRICE_FACTOR=1
    - PORT=3000
    command: "true"
  monitor:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    environment:
    - HOME_RPC_URL=http://parity1:8545
    - FOREIGN_RPC_URL=http://parity2:8545
    - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - HOME_DEPLOYMENT_BLOCK=0
    - FOREIGN_DEPLOYMENT_BLOCK=0
    - HOME_GAS_LIMIT=300000
    - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - HOME_GAS_PRICE_SPEED_TYPE=standard
    - HOME_GAS_PRICE_FALLBACK=1000000000
    - HOME_GAS_PRICE_FACTOR=1
    - FOREIGN_GAS_LIMIT=300000
    - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
    - FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - FOREIGN_GAS_PRICE_FALLBACK=1000000000
    - FOREIGN_GAS_PRICE_FACTOR=1
    - LEFT_TX_THRESHOLD=100
    - PORT=3003
    entrypoint: yarn start
    ports:
    - "3003:3003"
  e2e:
    build:
      context: ..
      dockerfile: Dockerfile.e2e
    command: "true"
