version: '3.8'
networks:
  ultimate:
    external: true
services:
  parity1:
    build: ../parity
    ports:
    - "8541:8545"
    networks:
      - ultimate
  parity2:
    build:
      context: ../parity
      dockerfile: Dockerfile-foreign
    ports:
    - "8542:8545"
    networks:
      - ultimate
  redis:
    image: "redis:4"
    networks:
      - ultimate
  rabbit:
    image: "rabbitmq:3-management"
    networks:
      - ultimate
  oracle:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-oracle:${ORACLE_TAG:-local}
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    env_file: ../e2e-commons/components-envs/oracle.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-erc20:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-oracle:${ORACLE_TAG:-local}
    env_file: ../e2e-commons/components-envs/oracle-erc20.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-erc20-native:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-oracle:${ORACLE_TAG:-local}
    env_file: ../e2e-commons/components-envs/oracle-erc20-native.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  oracle-amb:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-oracle:${ORACLE_TAG:-local}
    env_file: ../e2e-commons/components-envs/oracle-amb.env
    environment:
    - NODE_ENV=production
    command: "true"
    networks:
      - ultimate
  ui:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-ui:${UI_TAG:-local}
    build:
      context: ..
      dockerfile: ui/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/ui.env
    command: "true"
    networks:
      - ultimate
  ui-erc20:
    build:
      context: ..
      dockerfile: e2e-commons/Dockerfile.ui
      args:
        DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE:-tokenbridge}
        UI_TAG: ${UI_TAG:-local}
        DOT_ENV_PATH: e2e-commons/components-envs/ui-erc20.env
    command: "true"
    networks:
      - ultimate
  ui-erc20-native:
    build:
      context: ..
      dockerfile: e2e-commons/Dockerfile.ui
      args:
        DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE:-tokenbridge}
        UI_TAG: ${UI_TAG:-local}
        DOT_ENV_PATH: e2e-commons/components-envs/ui-erc20-native.env
    command: "true"
    networks:
      - ultimate
  ui-amb-stake-erc20-erc20:
    build:
      context: ..
      dockerfile: e2e-commons/Dockerfile.ui
      args:
        DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE:-tokenbridge}
        UI_TAG: ${UI_TAG:-local}
        DOT_ENV_PATH: e2e-commons/components-envs/ui-amb-stake-erc20-erc20.env
    command: "true"
    networks:
      - ultimate
  alm:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-alm:${ALM_TAG:-local}
    build:
      context: ..
      dockerfile: alm/Dockerfile
      args:
        DOT_ENV_PATH: e2e-commons/components-envs/alm.env
    command: "true"
    networks:
      - ultimate
  monitor:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-monitor:${MONITOR_TAG:-local}
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    env_file: ../e2e-commons/components-envs/monitor.env
    entrypoint: yarn check-and-start
    ports:
      - "3010:3010"
    networks:
      - ultimate
  monitor-erc20:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-monitor:${MONITOR_TAG:-local}
    env_file: ../e2e-commons/components-envs/monitor-erc20.env
    entrypoint: yarn check-and-start
    ports:
      - "3011:3011"
    networks:
      - ultimate
  monitor-erc20-native:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-monitor:${MONITOR_TAG:-local}
    env_file: ../e2e-commons/components-envs/monitor-erc20-native.env
    entrypoint: yarn check-and-start
    ports:
      - "3012:3012"
    networks:
      - ultimate
  monitor-amb:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-monitor:${MONITOR_TAG:-local}
    env_file: ../e2e-commons/components-envs/monitor-amb.env
    entrypoint: yarn check-and-start
    ports:
      - "3013:3013"
    networks:
      - ultimate
  e2e:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-e2e:${E2E_TAG:-local}
    build:
      context: ..
      dockerfile: Dockerfile.e2e
    command: "true"
    networks:
      - ultimate
  blocks:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-e2e:${E2E_TAG:-local}
    entrypoint: node e2e-commons/scripts/blocks.js
    networks:
      - ultimate
  molecule_runner:
    image: ${DOCKER_IMAGE_BASE:-tokenbridge}/tokenbridge-e2e-molecule_runner:${MOLECULE_RUNNER_TAG:-local}
    build:
      context: ..
      dockerfile: deployment-e2e/Dockerfile
    restart: 'no'
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/mono
