---
version: '3'
networks:
  ultimate:
    external: true
services:
  parity1:
    build: ../parity
    ports:
    - "8541:8545"
    networks:
      - ultimate
  parity2:
    build:
      context: ../parity
      dockerfile: Dockerfile-foreign
    ports:
    - "8542:8545"
    networks:
      - ultimate
  redis:
    image: "redis:4"
    networks:
      - ultimate
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    networks:
      - ultimate
  oracle:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - ORACLE_BRIDGE_MODE=NATIVE_TO_ERC
    - ORACLE_QUEUE_URL=amqp://rabbit
    - ORACLE_REDIS_URL=redis://redis
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
    - ORACLE_VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1
    - ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1
    - ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=0.1
    - ORACLE_HOME_RPC_POLLING_INTERVAL=500
    - ORACLE_FOREIGN_RPC_POLLING_INTERVAL=500
    - ORACLE_ALLOW_HTTP_FOR_RPC=yes
    command: "true"
    networks:
      - ultimate
  oracle-erc20:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - ORACLE_BRIDGE_MODE=ERC_TO_ERC
    - ORACLE_QUEUE_URL=amqp://rabbit
    - ORACLE_REDIS_URL=redis://redis
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
    - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
    - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
    - ORACLE_VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1
    - ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1
    - ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=0.1
    - ORACLE_HOME_RPC_POLLING_INTERVAL=500
    - ORACLE_FOREIGN_RPC_POLLING_INTERVAL=500
    - ORACLE_ALLOW_HTTP_FOR_RPC=yes
    command: "true"
    networks:
      - ultimate
  oracle-erc20-native:
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    environment:
    - NODE_ENV=production
    - ORACLE_BRIDGE_MODE=ERC_TO_NATIVE
    - ORACLE_QUEUE_URL=amqp://rabbit
    - ORACLE_REDIS_URL=redis://redis
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - ERC20_TOKEN_ADDRESS=0x3C665A31199694Bf723fD08844AD290207B5797f
    - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
    - ORACLE_VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
    - ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1
    - ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1
    - ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=0.1
    - ORACLE_HOME_RPC_POLLING_INTERVAL=500
    - ORACLE_FOREIGN_RPC_POLLING_INTERVAL=500
    - ORACLE_ALLOW_HTTP_FOR_RPC=yes
    command: "true"
    networks:
      - ultimate
  ui:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - COMMON_HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - COMMON_FOREIGN_RPC_URL=http://localhost:8542
    - COMMON_HOME_RPC_URL=http://localhost:8541
    - UI_NATIVE_TOKEN_DISPLAY_NAME=POA
    - UI_HOME_NETWORK_DISPLAY_NAME=Sokol
    - UI_FOREIGN_NETWORK_DISPLAY_NAME=Kovan
    - UI_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - UI_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - UI_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - UI_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=5000000000
    - UI_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - UI_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - UI_PORT=3000
    command: "true"
    networks:
      - ultimate
  ui-erc20:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - COMMON_HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
    - COMMON_FOREIGN_RPC_URL=http://localhost:8542
    - COMMON_HOME_RPC_URL=http://localhost:8541
    - UI_NATIVE_TOKEN_DISPLAY_NAME=POA
    - UI_HOME_NETWORK_DISPLAY_NAME=Sokol
    - UI_FOREIGN_NETWORK_DISPLAY_NAME=Kovan
    - UI_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - UI_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - UI_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - UI_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=5000000000
    - UI_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - UI_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - UI_PORT=3000
    command: "true"
    networks:
      - ultimate
  ui-erc20-native:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    environment:
    - COMMON_HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - COMMON_FOREIGN_RPC_URL=http://localhost:8542
    - COMMON_HOME_RPC_URL=http://localhost:8541
    - UI_NATIVE_TOKEN_DISPLAY_NAME=POA
    - UI_HOME_NETWORK_DISPLAY_NAME=Sokol
    - UI_FOREIGN_NETWORK_DISPLAY_NAME=Kovan
    - UI_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx//%s
    - UI_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
    - UI_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
    - UI_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=5000000000
    - UI_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=5000000000
    - UI_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - UI_PORT=3000
    command: "true"
    networks:
      - ultimate
  monitor:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    environment:
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
    - MONITOR_HOME_START_BLOCK=0
    - MONITOR_FOREIGN_START_BLOCK=0
    - MONITOR_VALIDATOR_HOME_TX_LIMIT=300000
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1000000000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - MONITOR_VALIDATOR_FOREIGN_TX_LIMIT=300000
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1000000000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - MONITOR_TX_NUMBER_THRESHOLD=100
    - MONITOR_PORT=3010
    entrypoint: yarn check-and-start
    ports:
      - "3010:3010"
    networks:
      - ultimate
  monitor-erc20:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    environment:
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x4a58D6d8D416a5fBCAcf3dC52eb8bE8948E25127
    - MONITOR_HOME_START_BLOCK=0
    - MONITOR_FOREIGN_START_BLOCK=0
    - MONITOR_VALIDATOR_HOME_TX_LIMIT=300000
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1000000000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - MONITOR_VALIDATOR_FOREIGN_TX_LIMIT=300000
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1000000000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - MONITOR_TX_NUMBER_THRESHOLD=100
    - MONITOR_PORT=3011
    entrypoint: yarn check-and-start
    ports:
      - "3011:3011"
    networks:
      - ultimate
  monitor-erc20-native:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    environment:
    - COMMON_HOME_RPC_URL=http://parity1:8545
    - COMMON_FOREIGN_RPC_URL=http://parity2:8545
    - COMMON_HOME_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - COMMON_FOREIGN_BRIDGE_ADDRESS=0x488Af810997eD1730cB3a3918cD83b3216E6eAda
    - MONITOR_HOME_START_BLOCK=0
    - MONITOR_FOREIGN_START_BLOCK=0
    - MONITOR_VALIDATOR_HOME_TX_LIMIT=300000
    - COMMON_HOME_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_HOME_GAS_PRICE_FALLBACK=1000000000
    - COMMON_HOME_GAS_PRICE_FACTOR=1
    - MONITOR_VALIDATOR_FOREIGN_TX_LIMIT=300000
    - COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=https://gasprice.poa.network/
    - COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
    - COMMON_FOREIGN_GAS_PRICE_FALLBACK=1000000000
    - COMMON_FOREIGN_GAS_PRICE_FACTOR=1
    - MONITOR_TX_NUMBER_THRESHOLD=100
    - MONITOR_PORT=3012
    entrypoint: yarn check-and-start
    ports:
      - "3012:3012"
    networks:
      - ultimate
  e2e:
    build:
      context: ..
      dockerfile: Dockerfile.e2e
    command: "true"
    networks:
      - ultimate
