### home side rpc
home_rpc_url: https://sokol.poa.network
home_rpc_port: 443

### foreign side rpc
foreign_rpc_url: https://kovan.infura.io/mew
foreign_rpc_port: 443

### bridge configs
bridge_deposit_relay_gas:    3000000
bridge_withdraw_relay_gas:   3000000
bridge_withdraw_confirm_gas: 3000000

bridge_authorities_requires_signatures: 1

bridge_home_required_confirmations: 0
bridge_foreign_required_confirmations: 0

bridge_home_contract_address: "0x98f7b68C0Ef6A7DA0Bb0E786144A87bfEcc5cbD1"
bridge_foreign_contract_address: "0x5c29759020Fa2251B6481A3Ac1Ee507Ddbdc075c"
bridge_home_contract_deploy: 2213129
bridge_foreign_contract_deploy: 7066466

bridge_home_poll_interval: 4
bridge_foreign_poll_interval: 3
