---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: oracle-host
    groups:
      - example
    children:
      - oracle_swarm
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../../../deployment/site.yml
  inventory:
    host_vars:
      oracle-host:
        ORACLE_VALIDATOR_KEYSTORE_PATH: "../../../e2e-commons/keystore.json"
        ORACLE_VALIDATOR_KEYSTORE_PASSWORD: "12345678"
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../tests/*
scenario:
  name: oracle
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
