---
- name: BC - set home and foreign variables from signer
  block:
    - set_fact:
        home_signer_address: "0x{{ (signer_keyfile|from_json).address }}"
        home_signer_keyfile: '{{ signer_keyfile }}'
        home_signer_password: "{{ signer_password }}"
    - set_fact:
        foreign_signer_address: "{{ home_signer_address }}"
        foreign_signer_keyfile: '{{ home_signer_keyfile }}'
        foreign_signer_password: "{{ home_signer_password }}"
    - set_fact:
        bridge_home_password_file: "password.txt"
        bridge_foreign_password_file: "password.txt"
  when: signer_keyfile|default("") != "" or signer_password|default("") != ""
