---
version: '2.4'
services:
  alm:
    build:
      context: ..
      dockerfile: alm/Dockerfile
    ports:
      - "${ALM_PORT}:${ALM_PORT}"
    env_file: ./.env
    environment: 
      - NODE_ENV=production
    restart: unless-stopped
    entrypoint: serve -p ${ALM_PORT} -s .
