---
version: '2.4'
services:
  alm:
    image: fusenet/alm:latest
    build:
      context: ..
      dockerfile: alm/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: ./.env
    environment: 
      - NODE_ENV=production
    restart: unless-stopped
    entrypoint: serve -p ${PORT} -s .
