---
- name: Check if remote computer is listening on standard ssh port
  become: no
  wait_for: port="{{ ansible_port | default(22) }}" state="started" host="{{ inventory_hostname }}" connect_timeout="3" timeout="4"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: port_used

- name: Set inventory ansible_port to custom
  set_fact: ansible_port="{{ custom_ssh_port }}"
  when: port_used.state is undefined

- name: Preconf - setup UFW firewall
  import_tasks: ufw.yml

- name: Preconf - sshd
  import_tasks: sshd.yml
  when: custom_ssh_port != ""  and custom_ssh_port != ansible_port | default(22)

- name: Preconf - create user
  import_tasks: create-user.yml

- name: Preconf - configure syslog forwarding
  import_tasks: syslog-forward.yml
  when: syslog_server_port != ""

- name: Preconf - run handlers immediately
  meta: flush_handlers
