---
- name: Preconf.Syslog forward - apt install rsyslog-gnutls package
  apt:
    name: rsyslog-gnutls
    state: present
    update_cache: yes

- name: Preconf.Syslog forward - download papertrail CA
  get_url:
    url: "https://papertrailapp.com/tools/papertrail-bundle.pem"
    checksum: "md5:ba3b40a34ec33ac0869fa5b17a0c80fc"
    dest: "/etc/papertrail-bundle.pem"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart rsyslog

- name: Preconf.Syslog forward - create client config
  template:
    src: "rsyslog-tls-client.conf.j2"
    dest: "/etc/rsyslog.d/tls-client.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart rsyslog
